# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Instasite' do
	pod "AFNetworking", "~> 2.0"
end

target 'InstasiteTests' do

end

target 'InstasiteUITests' do

end

